# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 212e95786c863f3629bfe97ec8616bd4b46492011c3ce230c541bc9cc56f83cf5358cb77cc1199a1c500da95ccde080bfcc9ecd85000b9ad2f635ebb59a32960

test:
  secret_key_base: c29f6282b2cf9ba7ca03349517748c72e6327e5827a0dcfd29b3f471e3111606e35f063c4e0e296ae2aa11180f6cdb1f7407ed1408a096d3c23bfbd20e913be7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
